name: Hello World
author: Peter Yefi
description: Hello world action
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Peter
outputs:
  time:
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
