name: Private Action
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            peteryefi
      - run: |
          echo ${{ steps.issue.output.issue }}
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "Peter Yefi"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
